name: "Doc Detective"
description: "Treat doc content as testable assertions to validate doc accuracy and product UX."
inputs:
  version:
    description: Specify the version of Doc Detective to use. This can be a specific version number or an NPM tag (like `latest`).
    required: true
    default: latest
  command:
    description: The command to run. Valid values are "runTests" and "runCoverage".
    required: true
    default: runTests
  config:
    description: Path to the configuration file.
    required: false
    default: .doc-detective.json
  input:
    description: Path to the input file or directory. Overrides the "input" field in the config file.
    required: false
    default: "."
  exitOnFail:
    description: Exit with a non-zero code if one or more tests fails. Default is "false". Only valid for the "runTests" command.
    required: false
    default: "false"
  createIssueOnFail:
    description: Create a GitHub issue if one or more tests fails. Default is "false". Only valid for the "runTests" command.
    required: false
    default: "false"
  token:
    description: The GitHub token to use for creating issues. Defaults to the token already available to the GitHub Action workflow. Only set this if you want to override the default token.
    required: false
    default: ${{ github.token }}
outputs:
  results:
    description: JSON-formatted results of the command.
runs:
  using: node20 # Specifies the node version
  main: dist/index.js # Path to the JavaScript file that will be executed
