name: Doc Detective
description: Treat doc content as testable assertions to validate doc accuracy and product UX.
author: Doc Detective
inputs:
  version:
    description: Specify the version of Doc Detective to use. This can be a specific version number or an NPM tag (like `latest`).
    required: true
    default: latest
  command:
    description: The command to run. Valid values are "runTests" and "runCoverage".
    required: true
    default: runTests
  config:
    description: Path to the configuration file.
    required: false
  input:
    description: Path to the input file or directory. Overrides the "input" field in the config file.
    required: false
  exit_on_fail:
    description: Exit with a non-zero code if one or more tests fails. Default is "false". Only valid for the "runTests" command.
    required: false
    default: "false"
  create_issue_on_fail:
    description: Create a GitHub issue if one or more tests fails. Default is "false". Only valid for the "runTests" command.
    required: false
    default: "false"
  issue_title:
    description: The title of the created GitHub issue. Only valid if "create_issue_on_fail" is set to "true".
    required: false
    default: "Doc Detective Failure"
  issue_body:
    description: The body of the created GitHub issue. Use the `$RESULTS` variable to insert the results object. Only valid if "create_issue_on_fail" is set to "true".
    required: false
    default: "Doc Detective run failed with the following results:$RESULTS"
  issue_labels:
    description: Comma-separated list of labels to apply to the GitHub issue. Only valid if "create_issue_on_fail" is set to "true".
    required: false
    default: "doc-detective"
  issue_assignees:
    description: Comma-separated list of GitHub usernames to assign to the GitHub issue. Only valid if "create_issue_on_fail" is set to "true".
    required: false
    default: ""
  token:
    description: The GitHub token to use for creating issues. Defaults to the token already available to the GitHub Action workflow. Only set this if you want to override the default token.
    required: false
    default: ${{ github.token }}
outputs:
  results:
    description: JSON-formatted results of the command.
runs:
  using: node20 # Specifies the node version
  main: dist/index.js # Path to the JavaScript file that will be executed
branding:
  icon: search # The icon to display in the GitHub Marketplace
  color: green # The color of the branding