on:
  workflow_dispatch:
    inputs:
      runner:
        description: runner
        required: true
        default: ubuntu-latest
      version:
        description: version
        required: false
        default: latest
      command:
        description: command
        required: false
        default: runTests
      config:
        description: config
        required: false
        default: ./artifacts/.doc-detective.json
      input:
        description: input
        required: false
        default: ./artifacts/doc-content-inline-tests.md
      exitOnFail:
        description: exitOnFail
        required: false
        default: 'false'
      createIssueOnFail:
        description: createIssueOnFail
        required: false
        default: 'false'
      issueTitle:
        description: issueTitle
        required: false
        default: 'Doc Detective Failure'
      issueBody:
        description: issueBody
        required: false
        default: 'Doc Detective run failed with the following results:\n$RESULTS'


jobs:
  
  run:
    runs-on: ${{ github.event.inputs.runner }}

    name: Run the action
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: 20
      - run: npm i -g doc-detective@${{ github.event.inputs.version }}
      - name: Run Doc Detective
        uses: ./ # Uses an action in the root directory
        id: dd
        with:
          version: ${{ github.event.inputs.version }}
          command: ${{ github.event.inputs.command }}
          config: ${{ github.event.inputs.config }}
          input: ${{ github.event.inputs.input }}
          exitOnFail: ${{ github.event.inputs.exitOnFail }}
          createIssueOnFail: ${{ github.event.inputs.createIssueOnFail }}
          issueTitle: ${{ github.event.inputs.issueTitle }}
          issueBody: ${{ github.event.inputs.issueBody }}
